settings: Remove "apps" form the Python path
This allows importing apps using `import name_of_app` in addition to
`import apps.name_of_app`. However, since some Django stuff (such as
`manage.py test`) uses the former, we changed the app's name to include
`app.` in their `AppConfig` objects. This means that if the former is
used, the apps name no longer matches, leading to an error like:

	RuntimeError: Model class people.models.artauser.ArtaUser doesn't
	  declare an explicit app_label and isn't in an application in
	  INSTALLED_APPS.

To prevent this, just remove `apps` from the Python path and enforce
using full path. Note that the app's label will still only be the last
part of its name, so e.g. in fixtures and foreignkeys, you still just
refer to a model as e.g. "people.ArtaUser".